version: '3.8'

services:
  prod-creator-credentials-ui:
    container_name: prod-creator-credentials-ui
    image: prod-creator-credentials-ui
    build:
      dockerfile: ./docker/Dockerfile.prod
      context: ../
      target: runner
    environment:
      FRONTEND_APP_PORT: ${FRONTEND_APP_PORT}
    ports:
      - ${FRONTEND_APP_PORT}:${FRONTEND_APP_PORT}
